version: '3'

services:
  sftp:
    build:
      context: .
      dockerfile: sftp.dockerfile
    ports:
      - '6060:22'
    volumes:
      - /sftp/share:/home

  sftp_retek:
    build:
      context: .
      dockerfile: sftp.dockerfile
    ports:
      - '6161:22'
    volumes:
      - /sftp/retek:/home
      - /sftp/data:/data

  mule-sstage-sftp:
    build:
      context: .
      dockerfile: sftp.dockerfile
    ports:
      - '2222:22'
    volumes:
      - /sftp/share1:/home
